### ISSUE TITLE
config.get(...) doesn't seem to be a function, and wont use production config

### ISSUE THREAD

**Issue by zachschultz** [jesseditson/node-config-heroku#3]
I'm trying to use this just as I'm using node-config, however `config.get()` isn't a function, and when I run on a production environment my production config JSON isn't being loaded or used.

Edit:

Realized that `heroku.json` is what the package will read from for 'production' variables, and I set up a hook using this command `config-heroku hook add heroku HEROKU_CONFIG <MY APP NAME HERE>`

**Comment by jesseditson** [comment]
Catching up on GH notifications - is this issue resolved for you?
